[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[context.production]
  branch = "master"

[context.staging]
  branch = "develop"

[context.deploy-preview]
# You can override build/publish if different
